hydrologie/xhydro

.github/workflows/bump-version.yml

* Adds force push to override branch protections.
* Add "workflow_dispatch" to allow for manual version increases.
More information: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

Allow the bumpversion workflow to override branch protections

---

.github/workflows/bump-version.yml
.github/workflows/gh-pages.yml
docs/installation.rst

There has been pressure to change what the primary development branch should be in GitHub/GitLab (https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/). The new cookiecutter was already adapted to `main`, so this should get all remaining workflows and docs onto the "main" page.

Update actions to reflect new primary branch name "main"

---

.cruft.json
CONTRIBUTING.rst
HISTORY.rst
setup.cfg
setup.py
tests/test_testing_utils.py
tests/test_xhydro.py
xhydro/__init__.py
xhydro/testing/__init__.py
xhydro/testing/utils.py
xhydro/utils.py

* Adds the `pymannkendall` library to the requirements
* Some formatting adjustments
No.
I've set the repo configuration to not allow pushes to `main` from admin-level users. Mistakes happen, no worries!

Fix Main branch

---

HISTORY.rst
tests/test_local.py
xhydro/frequency_analysis/local.py

- This PR fixes #41
* Uses a lazier method to detect which parameters are associated to a given distribution.
* `parametric_quantiles` now returns the actual return_level (e.g. [10, 20]) instead of the quantile (e.g. [0.9, 0.95]).
- The `return_level` dimension has changed to the return level, instead of the quantile.

Better detection of fit params

---

environment-dev.yml
environment.yml
setup.py
xhydro/frequency_analysis/local.py
xhydro/indicators.py

- No.
* Fix a few typing issues, including the lack of `Optional`.
* Remove `scipy` as a dependency, since changes in #43 removed the need to explicitly call it.
- No.

Small typing fixes

---

.cruft.json
.github/workflows/bump-version.yml
.readthedocs.yml
CHANGES.rst
environment-dev.yml
environment.yml
pyproject.toml
tests/test_xhydro.py
xhydro/__init__.py

* Prepares the release for 2023-12-01
No.

Prepare version 0.3.0

---

.pre-commit-config.yaml
CHANGES.rst
CONTRIBUTING.rst
environment-dev.yml
environment.yml
pyproject.toml
tox.ini
xhydro/cc.py
xhydro/indicators.py
xhydro/testing/__init__.py
xhydro/testing/helpers.py
xhydro/testing/utils.py

* Added `pooch` as a hard dependency (this can be revisited)
* Added `xhydro.testing.helpers.py` and `xhydro.testing.registry.txt`
* Added functions:
* `generate_registry`: Parses data found in package (`xhydro.testing.data`), and adds it to the `registry.txt`
* `load_registry`: Loads installed (or custom) registry and returns dictionary
* `populate_testing_data`: Fetches the registry and optionally caches files at a different location (helpful for `pytest-xdist`)
* Added a pre-commit hook for validating NumPy docstrings, fixed a few docstrings.
Yes. Testing data management is largely handled at the environment variable level:
* `XHYDRO_DATA_DIR` can be used to override the default cache location set for `pooch` (on *nix: `$XDG_CACHE_HOME`; Must be an absolute path)
* …

Testing data fetching via pooch

---

.github/workflows/actions-versions-updater.yml
.github/workflows/bump-version.yml
.github/workflows/first_pull_request.yml
.github/workflows/main.yml
.github/workflows/publish-pypi.yml
.github/workflows/tag-testpypi.yml
pyproject.toml

* Updates Workflows to use Organization-scoped Access Tokens
* Updates workflow permissions to be very explicit (easier to understand what access is being used/asked for by each)
No.
The `ACTIONS_VERSIONS_UPDATER_TOKEN` and the `BUMP_VERSION_TOKEN` are Organization-scoped (`Hydrologie`) personal access tokens with the following permissions for repositories `xhydro`, `xdatasets` and `xhydro-testdata`:
ACTIONS_VERSIONS_UPDATER_TOKEN:
- Contents: Read and Write
- Metadata: Read-Only
- Pull Requests: Read and Write
- Workflows: Read and Write
BUMP_VERSION_TOKEN:
- Contents: Read and Write
- Metadata: Read-Only
- Pull Requests: Read and Write
**Both are set to expire on January 1st, 2025**. After this point, anyone with maintainer access can generate new tokens and ask the …

Use organization-managed access tokens

---

.github/labeler.yml
.github/workflows/label.yml
.github/workflows/main.yml
CHANGES.rst
docs/notebooks/gis.ipynb
docs/notebooks/local_frequency_analysis.ipynb

* Adds an automation `labeler.yml` to the pull requests so that modifications to any notebooks found under `docs/notebooks` will add a "notebooks" label to the pull request.
* Adds a condition to the `Test Notebooks` job that triggers activation when a pull request has the `notebooks` label.
No.
`actions/labeler` is an officially-supported GitHub Action. Nevertheless, since it requires `pull_request_target` in order to run properly, permissions have been constrained and security is hardened.

Add notebooks label to pull requests when notebooks are modified

---

.github/workflows/bump-version.yml
.github/workflows/first_pull_request.yml
.github/workflows/main.yml
.github/workflows/publish-pypi.yml
.github/workflows/tag-testpypi.yml

* **[ad-m/github-push-action](https://github.com/ad-m/github-push-action)** published a new release **[v0.8.0](https://github.com/ad-m/github-push-action/releases/tag/v0.8.0)** on 2023-10-10T04:56:58Z
* **[actions/checkout](https://github.com/actions/checkout)** published a new release **[v4.1.1](https://github.com/actions/checkout/releases/tag/v4.1.1)** on 2023-10-17T15:53:17Z
* **[styfle/cancel-workflow-action](https://github.com/styfle/cancel-workflow-action)** published a new release **[0.12.1](https://github.com/styfle/cancel-workflow-action/releases/tag/0.12.1)** on 2024-01-25T16:36:58Z
* **[actions/github-script](https://github.com/actions/github-script)** published a new release **[v7.0.1](https://github.com/actions/github-script/releases/tag/v7.0.1)** on 2023-11-17T22:21:53Z
* …

[bot] Update GitHub Action Versions

---

.github/workflows/main.yml
CHANGES.rst
environment-dev.yml
environment.yml
pyproject.toml
tests/test_calibration.py
tests/test_indicators.py
tests/test_local.py
tests/test_testing_utils.py
xhydro/indicators.py
xhydro/modelling/hydrological_modelling.py
xhydro/modelling/obj_funcs.py

* Updates the xclim version to >=v0.48.0
* Adjusts some tests to be consistent with new freq strings and to reduce IDE/pytest warnings
* Adds a few missing functions to the API
* Specifies support for Python3.12
Yes. Python3.12 should now be supported.

Support xclim v0.48.0

---

CHANGES.rst
tests/test_optimal_interpolation.py
xhydro/optimal_interpolation/ECF_climate_correction.py
xhydro/optimal_interpolation/optimal_interpolation_fun.py
xhydro/optimal_interpolation/utilities.py

Added support for optimal interpolation of hydrological indicators.
No.
Added some flexibility for some parameters that were hard coded and are not optional inputs.

Oi indicators

---

CHANGELOG.rst
environment-dev.yml
environment.yml
pyproject.toml
tests/test_calibration.py
tests/test_ravenpy_models.py

* Pins `numpy` below v2.0.0 until dependencies can address changes
* Updates the `RavenPy` version to v0.15.0 (`RavenHydroFramework` v3.8.1).
Yes, the "Blended" model in RavenHydroFramwork v3.8.1 is completely broken (Segmentation faults). I'm not sure how mission-critical that is here.

Pin numpy below v2.0.0, bump RavenPy to v0.15.0

---

.github/workflows/dependency-review.yml
.github/workflows/main.yml
.pre-commit-config.yaml
.yamllint.yaml
CHANGELOG.rst

* Fixes the yamllint configuration and addresses inconsistencies that were silently ignored on Linux
* Implements a stricter and more consistent style
The yaml linting rule set is more strict about cosnistency:
- Line length has been bumped up to 180 characters (with exceptions for mappings and long words, such as URLs)
- Indentation must always be consistent
- Duplicate/mergeable keys are explicitly not allowed
- Brackets must always contain a leading and following space (for readability)
- Commas must always have a following space
- Newlines must always follow UNIX conventions
- Trailing spaces at the end of lines are not allowed (this is automatically addressed via pre-commit)
These rules will be merged upstream to the template and propagated elsewhere. Do we feel …

yamllint fixes

---

src/xhydro/frequency_analysis/local.py
tests/test_local.py

We default the fit function to the four laws giving the same results as RMCBestFit. For Hyfran, 3rd and 4th laws dont converge to the exact same parameters, but Scipy and RMCBest fit are probably more up to date.

changed default scipy_dist to those giving similar results then Hyfran

---

docs/notebooks/gis.ipynb
docs/notebooks/hydrological_modelling.ipynb
src/xhydro/gis.py

GIS module's tests were failing because the Planetary Computer's doesn't allow anonymous access to their blob storage anymore. However, they provide with their python API a way to sign (SAS token) the blobs allowing us to fetch the required files again. 
No

Fix gis module

---

.zenodo.json
AUTHORS.rst
src/xhydro/modelling/_ravenpy_models.py

Improved the _ravenpy_models.py script to be able to specify the rain snow fraction for all models, including HBVEC. With the new version of RavenPy (v0.16.0, unreleased), the rain_snow_fraction could be set with "RainSnowFraction=rain_snow_fraction" in the self.default_emulator_config dictionary. See: https://github.com/CSHS-CWRA/RavenPy/pull/408. For now (based on the latest release RavenPy version, v0.15.0) the change I'm suggesting here will enable changing the rain snow fraction algorithm for HBVEC as well.
None foreseen.

Improved the _ravenpy_models.py script to be able to specify the rain snow fraction for all models

---

CHANGELOG.rst
src/xhydro/frequency_analysis/local.py
tests/test_local.py

* Add a `periods` argument to `local.fit`, to compute multiple separate periods with a single call. Both `periods` and `horizon` follow `xscen` conventions.
- No. When `periods=None`, the function acts as before.

Add a `periods` argument to `local.fit`

---

CHANGELOG.rst
docs/notebooks/climate_change.ipynb
docs/notebooks/hydrological_modelling.ipynb
docs/notebooks/local_frequency_analysis.ipynb
docs/notebooks/optimal_interpolation.ipynb
docs/notebooks/pmp.ipynb
src/xhydro/testing/helpers.py
tests/conftest.py

* Adds a user-agent to the pooch call in order to deal with forbidden remote requests
* Fixes the URL joining logic in `load_registry` and `deveraux`
* Removes an unused import in `conftest.py`
No.
https://github.com/readthedocs/readthedocs.org/issues/11763

Update devereaux to add User-Agent to requests

---

src/xhydro/frequency_analysis/local.py

* Possibly a bug introduced by a recent release of `xarray` or `dask`. Fixes the `ValueError: dimensions ('dparams',) must have the same length as the number of data dimensions, ndim=2`).
The ValueError occurred if:
- The array was a dask object.
- The values in `dparams` were exactly those being selected (e.g. `["skew", "loc", "scale"]`) and a second selection (here, `scipy_dist`) was being made using a string.

Fix local.py

---

CHANGELOG.rst
Makefile
make-translations.bat

* Since we don't translate the outputs, we don't actually need to run the notebooks.

Skip notebook execution during translation
