hydrologie/xhydro

.cruft.json, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/first_pull_request.yml, .zenodo.json, AUTHORS.rst, HISTORY.rst, docs/conf.py, tests/test_xhydro.py
Template for PRs and `HISTORY.rst`
=> PR template

.pre-commit-config.yaml, .readthedocs.yml, .zenodo.json, HISTORY.rst, MANIFEST.in, README.rst, docs/conf.py, docs/index.rst, environment-docs.yml
- This PR fixes #22 
* Replaces the GitHub-hosted docs for ReadTheDocs
* Updates the version of mambaforge used to build the docs
* Updates Gabriel's affiliation info
Not really. The documentation target has changed, but everything is exactly the same.
We should probably disable the GitHub documentation deployment action.
=> Add ReadTheDocs

.github/workflows/publish-pypi.yml, .github/workflows/tag-testpypi.yml, HISTORY.rst
* `xhydro` now uses Trusted Publishing for deployments to PyPI and TestPyPI so that tokens are no longer required.
No.
https://docs.pypi.org/trusted-publishers/
=> Trusted Publishing for TestPyPI and PyPI

environment-dev.yml, environment.yml, pyproject.toml
* New frequencies in `pandas v2.2.0` are breaking a bunch of things. This is a temporary fix.
=> Temporary xclim pin

.github/workflows/main.yml, environment.yml
* pins `intake-esm` (needed for `xscen` and Python3.9)
No.
=> Pin intake-esm for Python3.9

.pre-commit-config.yaml, environment-dev.yml, pyproject.toml
* Updates the `ruff` configuration to silence warnings from the new configuration standard
* Adds `ruff` to the dependencies (should have already been there)
* Updates the `pre-commit` configuration
No.
https://docs.astral.sh/ruff
I'll be pushing this change here, then seeing what I can do about the linting errors in #88.
=> Ruff adjustments

.cruft.json, .github/workflows/bump-version.yml, .github/workflows/cache-cleaner.yml, .github/workflows/publish-pypi.yml, .github/workflows/tag-testpypi.yml, .pre-commit-config.yaml, .zenodo.json, CHANGES.rst, CONTRIBUTING.rst, docs/conf.py, environment-dev.yml, pyproject.toml, tests/test_calibration.py, tests/test_local.py, tests/test_xhydro.py, tox.ini
* Updates the cookiecutter template to the latest commit
* Addresses a handful of misconfigurations in the workflows
* Updates ruff to v0.2.0 and black to v24.2.0
No.
The `cache-cleaner.yml` workflow was missing a key permission to run properly. This is now fixed.
=> Update cookiecutter template

tests/test_testing_utils.py
* This test was too strict for our own good, so I removed it.
=> Less strict testing of version numbers in the Changelog

.cruft.json, CHANGES.rst, pyproject.toml, tests/test_xhydro.py, xhydro/__init__.py
* Prepares the next patch release (v0.3.4)
No.
=> Prepare 0.3.4

CHANGES.rst, docs/index.rst, docs/notebooks/index.rst, docs/usage.rst
- This PR fixes #114 
* Move all notebooks under a "Usage" section.
=> Move notebooks to their own section

.cruft.json, CHANGES.rst, pyproject.toml, tests/test_xhydro.py, xhydro/__init__.py
=> Prepare 0.3.5

.cruft.json, CHANGELOG.rst, pyproject.toml, src/xhydro/__init__.py, tests/test_xhydro.py
=> Prepare 0.3.6

CHANGELOG.rst, src/xhydro/cc.py, src/xhydro/frequency_analysis/local.py
* Either `apply_ufunc` has become more picky, or something changed in the behavior of the output of `fit`. Multiple functions failed because there were chunks on the `dparams` dimension. 
* No.
=> Fix bad chunking for parametric quantile

.cruft.json, .pre-commit-config.yaml, CI/requirements_ci.in, CI/requirements_ci.txt, Makefile, environment-dev.yml, environment.yml, pyproject.toml, src/xhydro/gis.py, tox.ini
* Updates the template, mostly dependency updates.
* Adds a version pin for `stackstac` and updates a call to be compliant with the new API
This updates the `numpydoc-validate` call to the new conventions
=> Fast-forward template

environment-dev.yml, environment.yml
xarray 2024.09 was temporarily excluded while xclim was waiting for a fix. This temporary fix is removed in this PR
=> xarray 2024.09 support

.cruft.json, CHANGELOG.rst, pyproject.toml, src/xhydro/__init__.py, tests/test_xhydro.py
* Prepares the next minor release
No.
The autoformatting for version bumping isn't great. I'm going to redesign it upstream to be a tad simpler/more useful.
I'll also be proposing this version for acceptance into the `conda-forge` repository. It's reached an adequate level of stability, IMO.
=> Prepare v0.4.0

environment-dev.yml, environment.yml, pyproject.toml
=> pin rasterio <=1.3.11

.cruft.json, .github/workflows/publish-pypi.yml, .github/workflows/tag-testpypi.yml, CHANGELOG.rst, pyproject.toml, src/xhydro/__init__.py, tests/test_xhydro.py
=> Prepare 0.4.1

.github/workflows/main.yml, CHANGELOG.rst, Makefile
- No.
* We already run ReadTheDocs once PRs are approved, so we don't need to run as many tests on the notebooks themselves.
=> Run less tests on Notebooks

docs/notebooks/gis.ipynb, environment-dev.yml, environment.yml, pyproject.toml
* The newest `xarray` breaks some things in`xclim v0.53.2`, but we can't update `xclim` until `ravenpy` has a release 💀
=> Temporary pin on xarray

Makefile, src/xhydro/extreme_value_analysis/julia_import.py, tests/test_extremes.py
* Revert the changes to Makefile (which were broken).
=> Revert change to makefile, fix typo

.cruft.json, CHANGELOG.rst, pyproject.toml, src/xhydro/__init__.py, tests/test_xhydro.py
=> Prepare 0.5.0

CHANGELOG.rst
Forgot to update Changelog in (:pull:`317`)
=> Forgot to update changelog in PR #317

.github/workflows/cache-cleaner.yml
* Fixes a connection issue needed for a workflow.
No.
=> Update allowed connections

CHANGELOG.rst, SECURITY.md
* Adds a security policy to the repository
No.
This change adds a security policy, which details a few important pieces of information:
- How often we perform regular releases
- Which versions will receive critical security updates
- How to contact the developers concerning sensitive issues
This is a very standard notice to have and will be added to other `Hydrologie` repositories as well.
=> Add a security policy

CHANGELOG.rst, src/xhydro/modelling/_ravenpy_models.py, src/xhydro/modelling/hydrological_modelling.py, tests/test_hydrological_modelling.py, tests/test_ravenpy_models.py
=> Fix bad dimension order in distributed Raven
